"use strict";

try {

    let x = 0;

} catch(error){

    console.log(error);

}finally{
    //Finaly es opcional
    console.log("Se Termina la revicion de errores");
}